version: '3.8'

services:
  django:
    container_name: django
    build: 
      context: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: ./.env.dev
    depends_on:
      - celery-beat
      - redis
      - pgdb

  celery:
    build: 
      context: .
    command: celery -A youtube_video_search worker --loglevel=INFO -E
    env_file: ./.env.dev
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: 
      context: .
    command: celery -A youtube_video_search beat --loglevel=INFO
    env_file: ./.env.dev
    volumes:
      - .:/app
    depends_on:
      - redis
  pgdb:
      image: postgres:13.0-alpine
      restart: unless-stopped
      volumes:
          - pgdata:/var/lib/postgresql/data/
      env_file: ./.env.dev
      expose:
          - 5432    
  redis:
    image: "redis:alpine"
    expose:
      - "6379:6379"

volumes:
  pgdata:
