version: '3.8'

services:
  django:
    restart: unless-stopped
    build: .
    container_name: django
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - celery
      - redis
  celery:
    restart: unless-stopped
    build: 
      context: .
    command: celery -A youtube_video_search beat --loglevel=INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - 6379

volumes:
  pgdata:
